---
title: "Linear Regression Via Category Theory"
author: "Bradley Saul"
date: 2022-06-20T14:19:14-05:00
tags: ["Haskell", "R", "statistics", "linear model", "category theory"]
---

A couple of years ago, 
I read 
[Conal Elliot's](http://conal.net/)
[Compiling to Categories](http://conal.net/papers/compiling-to-categories/) paper.
I thought at the time "Wow, this is amazing",
but I didn't have the key that made the ideas concrete for me.
[Chris Penner's](https://chrispenner.ca/)
talk on 
[deconstructing lambdas](https://www.youtube.com/watch?v=xZmPuz9m2t0)
unlocked Conal's paper for me.
In today's post,
I'm making sure I understand the basics by implementing the 
[ordinary least squares estimator](https://en.wikipedia.org/wiki/Ordinary_least_squares)
using categories.

The key idea of "Compiling to Categories" is right there in the first sentence:

> As discovered by [Joachim Lambek](https://en.wikipedia.org/wiki/Joachim_Lambek), 
> the models of the simply typed λ-calculus (STLC)
> are exactly the cartesian closed categories (CCC).

In other words, programming in a cartesian closed category _is_
programming in a simply typed λ-calculus.
Or more specifically,
the STLC/CCC relationship means
one can program using categories and compile to any language
that supports a STLC.
If you're not familiar with either the λ-calculus or category theory, that's fine.
My goal here is not to go in depth into the concepts,
instead I hope my example is a teaser for statisticians
to engage with category theory.

For this post I'm going write a single program for the following, 
a formula statisticians will be familiar with:

\(
\hat{\beta} = (X^{\intercal}X)^{-1}X^{\intercal}Y.
\)

Then I will compile this program into multiple target languages, namely 
[Haskell](https://www.haskell.org/) 
and 
[R](https://www.r-project.org/).

## Categorical Building Blocks

A category in mathematics is comprised of 
a set of objects,
a set of arrow (morphisms) between objects,
and way of composing arrows together subject to certain laws
([more details for the uninitiated here](https://en.wikipedia.org/wiki/Category_theory#Categories,_objects,_and_morphisms)).
In Haskell, a category can be represented by a typeclass `Category`
where the category is parameterized the type of its arrows:

```
class Category k where
  -- The identity morphism takes an object A and returns A
  id :: a `k` a
  -- The composition rule says that for any two morphisms A --> B and B --> C,
  -- there exists a morphism A --> C. 
  -- This is encoded by a Haskell function that transforms the morphisms.
  (>>>) :: a `k` b -> b `k` c -> a `k` c
```

Similar to equipping sets with additional structure,
categories can have additional structure too.
In particular, a *Cartesian* category comes equipped with products:
a way to stick two things together into a pair and get them back out.

```haskell
class Category k => Cartesian k where
  exl :: (l, r) `k` l
  exr :: (l, r) `k` r
  (△) :: a `k` c -> a `k` d -> a `k` (c, d)
```

The added structure that products impart is quite useful. 
For example, we now have a way to copy data.

```haskell
copy :: (Cartesian k) =>  a `k` (a, a)
copy = id △ id
```

The cartesian structure also provides
a way to swap the order of elements in a pair.

```haskell
swap :: (Cartesian k) => (a, b) `k` (b, a)
swap = exr △ exl
```

We now have almost all the tools we need in terms of category theory.
The [`Strong` class](https://hackage.haskell.org/package/profunctors-5.6.2/docs/Data-Profunctor.html#t:Strong)
provides a way of embedding morphisms within a higher-order structure.
Conal's paper doesn't use `Strong` (at least that I can tell),
but the utilities available once we have it are useful.
I'm not sure where the term "strong" comes from.


```haskell
class Category k => Strong k where
  first :: a `k` b -> (a, other) `k` (b, other)
  second :: a `k` b -> (other, a) `k` (other, b)
```



## Compilation of Categories

## Try it out

## Notes

* In principle, I could have started with the least squares objective function
and [automatically derive the solution](http://conal.net/papers/essence-of-ad/)
using category theory.


