baseURL = "https://www.functionalstatistics.com"
title = "Functional Statistics"

theme = "bslabs"

languageCode = "en"
defaultContentLanguage = "en"

paginate = 20

pygmentsStyle = "xcode"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

#disqusShortname = "yourdiscussshortname"
ignoreFiles = [ "\\.Rmd$"
                , "\\.Rmarkdown$"
                , "_cache$"
                , "\\.knit\\.md$"
                , "\\.utf8\\.md$"
                , "(^|/)renv$"
                , "renv\\.lock$"
                , "\\.agdai"
                ]

[params]
    author = "Bradley Saul"
    description = "Functional Programming, Causal Inference, Ecology and Conservation"
    keywords = "blog,developer,statistian"
    info = "Statistician, Functional Programmer"
    avatarURL = "images/babytar.jpg"
    #gravatar = "john.doe@example.com"
    footerContent = ""

    dateFormat = "2006-01-02"

    hideFooter = false
    hideCredits = false
    hideCopyright = false
    since = 2021
    
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "11.5.1"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "haskell", "julia", "yaml"]
    highlightjsTheme = "base16/monokai"
    
    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorScheme = "auto"

    # Hide the toggle button, along with the associated vertical divider
    hideColorSchemeToggle = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = true

    # Custom CSS
    customCSS = []

    # Custom SCSS
    customSCSS = []

    # Custom JS
    customJS = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
[params.fathomAnalytics]
    siteID = "ABCDE"
    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
    serverURL = "analytics.example.com"

# If you want to use plausible(https://plausible.io) for analytics, add this section
[params.plausibleAnalytics]
    domain = "example.com"
    # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
    serverURL = "analytics.example.com"

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
[params.goatCounter]
    code = "code"

# If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
[params.cloudflare]
    token = "token"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 1
    url = "https://github.com/bsaul/"
#[[params.social]]
#    name = "Gitlab"
#    icon = "fa fa-gitlab"
#    weight = 2
#    url = "https://gitlab.com/johndoe/"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter"
    weight = 3
    url = "https://twitter.com/bradleysaul/"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/bradleysaul/"
#[[params.social]]
#    name = "Scholar"
#    #icon = "fa fa-linkedin"
#    weight = 5
#    url = "https://scholar.google.com/citations?user=7rYgr1sAAAAJ&hl=en"
#[[params.social]]
#    name = "Medium"
#    icon = "fa fa-medium"
#    weight = 5
#    url = "https://medium.com/@johndoe"
[[params.social]]
    name = "RSS"
    icon = "fa fa-rss"
    weight = 6
    url = "https://www.functionalstatistics.com/index.xml"
    rel = "alternate"
    type = "application/rss+xml"


[languages]
    [languages.en]
        languageName = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            #[[languages.en.menu.main]]
            #name = "Research"
            #weight = 3
            #url = "research/"


            [[languages.en.menu.main]]
            name = "Software"
            weight = 4
            url = "software/"
            
            [[languages.en.menu.main]]
            name = "Contact me"
            weight = 5
            url = "contact/"
